### PR TITLE
add company.name to request variables

### PR DESCRIPTION
**Pull request by ros3bud**
I needed to make this update because of the recent update to the standard fields repository with company.name replacing company.

### CODE REVIEW

**Comment by ros3bud** [comment]
@zalary, lgty?

**Comment by zalary** [comment]
it looks like this commit checks for the existence of company name before titleizing it but doesn't add it to the request variables.

**Comment by ros3bud** [comment]
@zalary updated. :innocent:

**Comment by zalary** [comment]
LGTM :sunglasses:

**Pull request merged**
