### PR TITLE
Update email parsing

### PR DESCRIPTION
**Pull request by ros3bud**
@cgrayson, I needed to revert to the for statement to add some more parsing based on the value. This is because different values are passed for email depending on the error. LGTY?

### CODE REVIEW

**Comment by cgrayson** [comment]
What didn't you like about doing it [like this](https://github.com/activeprospect/leadconduit-integration-lendio/commit/6e7972b1d29ff28419bc7366868023b0e82f3a06#diff-97ed8065a499343c33ca0a10a8ca63ac)? 

Also, I think it's worth taking a minute or two to open issues for these changes, so we can see a little more of why they're needed, maybe a link to test leads or info from the Lendio API docs/team. That would also be useful for tracking, and for future reference.

**Comment by ros3bud** [comment]
I was concerned that more error messages from values may present themselves, so this seemed more conducive to allowing for that possibility. Also, noted regarding your suggestion about tracking issues.

**Comment by cgrayson** [comment]
I still like the `switch` a little better, but it's your call. 

LGTM

**Comment by ros3bud** [comment]
Noted @cgrayson - I will leave it this way for now, but keep an eye on things.

**Pull request merged**
